# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask
        pip install flask-sqlalchemy
        pip install Flask-Cors
        pip install mysql-connector
        pip install python-dotenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run our unit tests
      env: # Or as an environment variable
        PASSWORD: ${{ secrets.PASSWORD }}
      run: |
        cd server
        python position_test.py
        python skill_test.py
        python course_test.py
        python staff_test.py
        python learning_journey_test.py
